name: C/C++ CI with CMake

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      run: sudo apt-get install -y cmake
    - name: Configure with CMake
      run: cmake -S . -B build
    - name: Build with CMake
      run: cmake --build build
    - name: Upload Binary as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binary
        path: build/a.out